### ISSUE TITLE
Unable to run playbook with inventory as a argument.

### ISSUE THREAD

**Issue by Rajendraladkat1919** [geektechdude/ansible_container#2]
Hi,

I am trying to run playbook from my local machine with inventory as argument with below command but ran into below issues.

```
docker run --rm --network host -v /home/centos/local-test/rala-v2:/tmp/rala-v2 philm/ansible_playbook:latest -i /tmp/rala-v2/runners/src/test/bashscript/inventory.sh  /tmp/rala-v2/runners/src/test/ansible/hadoopenv.yml
ERROR! Attempted to execute "/tmp/rala-v2/runners/src/test/bashscript/inventory.sh" as inventory script: problem running /tmp/rala-v2/runners/src/test/bashscript/inventory.sh --list ([Errno 2] No such file or directory)
[centos@sql-common test]$ docker run --rm --network host -v /home/centos/local-test/rala-v2:/tmp/rala-v2 philm/ansible_playbook:latest /tmp/rala-v2/runners/src/test/ansible/hadoopenv.yml

PLAY RECAP *********************************************************************
```
So just need to know if I have  to pass inventory and playbook from local host how can I achieve this using current docker image.

**Comment by geektechdude** [comment]
Hi, 

The above looks like you are running philm/ansible_playbook and not my Docker image. I detailed some of the commands in a blog post at https://geektechstuff.com/2020/02/10/ansible-in-a-docker-container/ , does that help?

If not reply here and I'll take a look.

**Comment by Rajendraladkat1919** [comment]
Will keep you posted on this.

**Comment by Rajendraladkat1919** [comment]
Your image is working fine. There is actual problem with targeted Machine. Please  close this issue.
